name: build release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prereqs install
      run: |
        sudo apt install libdbus-1-dev pkg-config

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-unknown-linux-gnu
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-apple-darwin
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true
  
  release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux-x86]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu

      - name: hawk tuah
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: |
            x86_64-unknown-linux-gnu
            aarch64-apple-darwin
