name: build release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prereqs install
      run: |
        sudo apt install libdbus-1-dev pkg-config

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-unknown-linux-gnu.bin
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-apple-darwin.bin
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true
  
  release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux-x86]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin.bin
          path: dist/aarch64-apple-darwin.bin
          
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu.bin
          path: dist/x86_64-unknown-linux-gnu.bin

      - name: ls
        run: ls -la dist

      - name: hawk tuah
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: ${{ secrets.GH_TOKEN }}
          files: dist/*
