name: rust build pipeline

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prereqs install
      run: |
        apt install libdbus-1-dev pkg-config

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-unknown-linux-gnu
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: run build
      run: cargo build --release

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-apple-darwin
        path: ./target/release/sfs-cli
        retention-days: 1
        overwrite: true
  
  release:
    
