name: rust build pipeline

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add aarch64-apple-darwin target
      run: rustup target add aarch64-apple-darwin
    
    - name: run build
      run: cargo build --target aarch64-apple-darwin
