name: rust build pipeline

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prereqs
      run: |
        apt install libdbus-1-dev pkg-config

    - name: add targets
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add aarch64-unknown-linux-gnu
    
    - name: run build (x86)
      run: cargo build --target x86_64-unknown-linux-gnu

    - name: run build (arm)
      run: cargo build --target aarch64-unknown-linux-gnu
